In [1]:
# Data Loading

import pandas as pd
from pathlib import Path

# Find CSV files in the project folder
csv_files = Path("..").rglob("*.csv")

# Store datasets
data = {}

# Load each CSV file
for file in csv_files:
    dataset_name = file.stem
    data[dataset_name] = pd.read_csv(file)

# Display loaded datasets
for name, df in data.items():
    print(f"{name}: {df.shape}")

customers: (1006, 4)
kitchens: (25, 5)
menu_items: (45270, 6)
orders: (20120, 10)

In [2]:
# Dataset Profiling

for name, df in data.items():
    print(f"\n{'='*50}")
    print(name.upper())
    print(f"\n{'='*50}")

    print("Rows:", df.shape[0])
    print("Column:",df.shape[1])
    print("Missing Values:", df.isna().sum().sum())
    print("Duplicate rows:", df.duplicated().sum())

==================================================
CUSTOMERS

==================================================
Rows: 1006
Column: 4
Missing Values: 10
Duplicate rows: 6

==================================================
KITCHENS

==================================================
Rows: 25
Column: 5
Missing Values: 0
Duplicate rows: 0

==================================================
MENU_ITEMS

==================================================
Rows: 45270
Column: 6
Missing Values: 452
Duplicate rows: 270

==================================================
ORDERS

==================================================
Rows: 20120
Column: 10
Missing Values: 1649
Duplicate rows: 120

In [4]:
# Numeric Profiling

for name, df in data.items():
    print(f"\n{'='*50}")
    print(name.upper())
    print(f"\n{'='*50}")

    display(df.describe().T)

==================================================
CUSTOMERS

==================================================

                 count unique         top freq
customer_id       1006   1000   CUS-00412    2
city              1006     21      Mumbai  202
signup_date       1006    549  2025-06-16    8
customer_segment   996      3     Regular  548

==================================================
KITCHENS

==================================================

,count,mean,std,min,25%,50%,75%,max
monthly_rent,25.0,120662.52,53004.615415,66487.0,73989.0,105396.0,135636.0,235348.0
staff_count,25.0,11.28,5.511503,4.0,7.0,11.0,13.0,23.0

==================================================
MENU_ITEMS

==================================================

,count,mean,std,min,25%,50%,75%,max
quantity,45270.0,1.971681,1.132399,0.00,1.00,2.00,3.0000,5.00
unit_price,44818.0,203.001746,97.211544,-419.83,134.42,188.01,250.1075,549.76

==================================================
ORDERS

==================================================

,count,mean,std,min,25%,50%,75%,max
order_value,19960.0,575.760832,356.920907,-294.93,342.29,493.965,717.8275,5977.13
discount,20120.0,18.510025,52.146514,0.00,0.00,0.000,14.7125,874.16
delivery_fee,19959.0,51.445389,30.235607,-48.14,28.70,41.710,64.2600,169.89
delivery_distance_km,19504.0,5.257035,4.966389,0.00,1.46,3.650,7.4325,34.07
delivery_time_min,19408.0,29.424036,17.771148,0.00,15.70,25.400,38.2000,155.50

In [6]:
# Identify Data Quality Issue

for name, df in data.items():
    print(f"\n{'='*50}")
    print(name.upper())
    print(f"\n{'='*50}")

    display(df.describe().T)

    missing=df.isna().sum()
    missing_pct = (missing/len(df)*100).round(2)

    profile=pd.DataFrame({
        "missing_count": missing,
        "missing_pct": missing_pct
    })

    display(profile[profile["missing_count"]>0])

==================================================
CUSTOMERS

==================================================

                 count unique         top freq
customer_id       1006   1000   CUS-00412    2
city              1006     21      Mumbai  202
signup_date       1006    549  2025-06-16    8
customer_segment   996      3     Regular  548

                  missing_count  missing_pct
customer_segment             10         0.99

==================================================
KITCHENS

==================================================

,count,mean,std,min,25%,50%,75%,max
monthly_rent,25.0,120662.52,53004.615415,66487.0,73989.0,105396.0,135636.0,235348.0
staff_count,25.0,11.28,5.511503,4.0,7.0,11.0,13.0,23.0

Empty DataFrame
Columns: [missing_count, missing_pct]
Index: []

==================================================
MENU_ITEMS

==================================================

,count,mean,std,min,25%,50%,75%,max
quantity,45270.0,1.971681,1.132399,0.00,1.00,2.00,3.0000,5.00
unit_price,44818.0,203.001746,97.211544,-419.83,134.42,188.01,250.1075,549.76

            missing_count  missing_pct
unit_price            452          1.0

==================================================
ORDERS

==================================================

,count,mean,std,min,25%,50%,75%,max
order_value,19960.0,575.760832,356.920907,-294.93,342.29,493.965,717.8275,5977.13
discount,20120.0,18.510025,52.146514,0.00,0.00,0.000,14.7125,874.16
delivery_fee,19959.0,51.445389,30.235607,-48.14,28.70,41.710,64.2600,169.89
delivery_distance_km,19504.0,5.257035,4.966389,0.00,1.46,3.650,7.4325,34.07
delivery_time_min,19408.0,29.424036,17.771148,0.00,15.70,25.400,38.2000,155.50

                      missing_count  missing_pct
order_value                     160         0.80
delivery_fee                    161         0.80
delivery_distance_km            616         3.06
delivery_time_min               712         3.54

In [7]:
# Data quality issue summary
for name, df in data.items():
    print(f"\n{'='*50}")
    print(name.upper())
    print(f"\n{'='*50}")

    print("Duplicate rows:", df.duplicated().sum())
    print("Total Missing Values:", df.isna().sum().sum())

==================================================
CUSTOMERS

==================================================
Duplicate rows: 6
Total Missing Values: 10

==================================================
KITCHENS

==================================================
Duplicate rows: 0
Total Missing Values: 0

==================================================
MENU_ITEMS

==================================================
Duplicate rows: 270
Total Missing Values: 452

==================================================
ORDERS

==================================================
Duplicate rows: 120
Total Missing Values: 1649